// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Calender: typeof import('./src/components/WelcomePage/Calender.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HeadBar: typeof import('./src/components/Common/HeadBar.vue')['default']
    HwtList: typeof import('./src/components/WelcomePage/HwtList.vue')['default']
    InformList: typeof import('./src/components/WelcomePage/InformList.vue')['default']
    LessonList: typeof import('./src/components/WelcomePage/LessonList.vue')['default']
    LessonMain: typeof import('./src/components/Lesson/LessonMain.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NotifyList: typeof import('./src/components/WelcomePage/NotifyList.vue')['default']
    NotifyListDetail: typeof import('./src/components/WelcomePage/NotifyListDetail.vue')['default']
    ProfileMain: typeof import('./src/components/Profile/ProfileMain.vue')['default']
    SideBar: typeof import('./src/components/Common/SideBar.vue')['default']
    UserInfo: typeof import('./src/components/WelcomePage/UserInfo.vue')['default']
    WelcomeMain: typeof import('./src/components/WelcomePage/WelcomeMain.vue')['default']
  }
}

export { }
